export const products = [
  {
    part_number: "VL-DA60MO",
    title: "LED лампа VIDEX Filament VL-DA60MO 4W E27 3000K Porcelain dimmable",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "А60" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "400 Lm" },
      { key: "Максимальна сила струму", value: "33mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "60mm х 105mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "100шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484466" },
      { key: "Штрих-код", value: "4820246484466" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 319.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/45fb138b-f0d3-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/950c5b33-2547-488c-b6f3-d5a63ae1c07e.zip",
  },
  {
    part_number: "VL-DBMC100162",
    title:
      "LED лампа VIDEX Filament VL-DBMC100162 4W E27 1800K Black Chainmail style",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "140 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "100mm x 162mm" },
      { key: "Енергоефективність", value: "35 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484473" },
      { key: "Штрих-код", value: "4820246484473" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1146.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/c5822fb3-f0d4-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/5bae5445-3d25-4a91-b4a2-ea6199e2f909.zip",
  },
  {
    part_number: "VL-DBMC125150",
    title:
      "LED лампа VIDEX Filament VL-DBMC125150 4W E27 1800K Black Chainmail style",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "140 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 150mm" },
      { key: "Енергоефективність", value: "35 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484381" },
      { key: "Штрих-код", value: "4820246484381" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1041.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/2c29f948-f0d5-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/7603b94d-8b6d-42ef-a494-d8412d5cc9ba.zip",
  },
  {
    part_number: "VL-DG125-BB80LF",
    title:
      "LED лампа VIDEX Filament VL-DG125-BB80LF 3.5W E27 3000K Bulb in bulb",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "3.5 W" },
      { key: "Світловий потік", value: "240 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "68 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484503" },
      { key: "Штрих-код", value: "4820246484503" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1170.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/4f9a634d-f0d9-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/7cf16757-bffc-430e-add6-336fe572fe38.zip",
  },
  {
    part_number: "VL-DG125175-WZTMO",
    title: "LED лампа VIDEX Filament VL-DG125175-WZTMO 4W E27 3000K Matt opal",
    params: [
      // ... (previous params)
      { key: "Розміри", value: "125mm x 175mm" },
      { key: "Енергоефективність", value: "125 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484541" },
      { key: "Штрих-код", value: "4820246484541" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 987.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/d9d33efb-f0d8-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/b95da2e7-1a81-4c9b-a92d-c62dad64a297.zip",
  },
  {
    part_number: "VL-DG125BN",
    title:
      "LED лампа VIDEX Filament VL-DG125BN 6W E27 1800K Black Magician pine needles",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "250 Lm" },
      { key: "Максимальна сила струму", value: "39mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 170mm" },
      { key: "Енергоефективність", value: "42 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484510" },
      { key: "Штрих-код", value: "4820246484510" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1095.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/a93ccda9-f0da-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/32e1b824-b353-4ba6-a0ba-496d8949477a.zip",
  },
  {
    part_number: "VL-DG125BP",
    title:
      "LED лампа VIDEX Filament VL-DG125BP 6W E27 1800K Black Magician net",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "180 Lm" },
      { key: "Максимальна сила струму", value: "39mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 170mm" },
      { key: "Енергоефективність", value: "30 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484527" },
      { key: "Штрих-код", value: "4820246484527" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1221.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/9651abfc-f0db-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/b5158ea0-c55c-4b8e-bafd-04778a155512.zip",
  },
  {
    part_number: "VL-DG125MO",
    title:
      "LED лампа VIDEX Filament VL-DG125MO 7W E27 3000K Porcelain dimmable",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "806 Lm" },
      { key: "Максимальна сила струму", value: "33mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 170mm" },
      { key: "Енергоефективність", value: "115 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484534" },
      { key: "Штрих-код", value: "4820246484534" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 507.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/003dd33f-f0e8-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/0f6fcc10-d3c3-43f2-a74e-e3863c3b5ee8.zip",
  },
  {
    part_number: "VL-DG45MO",
    title: "LED лампа VIDEX Filament VL-DG45MO 4W E27 3000K Porcelain dimmable",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G45" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "400 Lm" },
      { key: "Максимальна сила струму", value: "20mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "45mm х 77mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "200шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484480" },
      { key: "Штрих-код", value: "4820246484480" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 287.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/eb863a26-f0e8-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/2a1aa125-fc5d-4729-99e8-72123c93c43e.zip",
  },
  {
    part_number: "VL-DG80MO",
    title: "LED лампа VIDEX Filament VL-DG80MO 7W E27 3000K Porcelain dimmable",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "806 Lm" },
      { key: "Максимальна сила струму", value: "33mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "80mm х 120mm" },
      { key: "Енергоефективність", value: "115 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "50шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484497" },
      { key: "Штрих-код", value: "4820246484497" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 693.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/852b9409-f0eb-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/fc130d45-eb00-4237-b12f-3fecce924e51.zip",
  },
  {
    part_number: "VL-DI-G125FC1979S",
    title: "LED лампа VIDEX Filament VL-DI-G125FC1979S 4W E27 1800K Smoke",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "100 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "25 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "10шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484398" },
      { key: "Штрих-код", value: "4820246484398" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1014.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/9e00cb5e-f0ef-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/a5109a46-b30c-4265-8e81-320c6bd11955.zip",
  },
  {
    part_number: "VL-DI-G125FC1980",
    title: "LED лампа VIDEX Filament VL-DI-G125FC1980 4W E27 1800K",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "180 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "45 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "10шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484404" },
      { key: "Штрих-код", value: "4820246484404" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 867.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/11503596-f0f0-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/83786870-187f-4ef9-8fa4-dfb305a4a0ea.zip",
  },
  {
    part_number: "VL-DI-G125FC1980S",
    title: "LED лампа VIDEX Filament VL-DI-G125FC1980S 4W E27 1800K Smoke",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "100 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "25 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "10шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484411" },
      { key: "Штрих-код", value: "4820246484411" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 867.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/ed29b975-f0f0-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/dacf63a4-9c3a-49ee-924c-1dbb439b44f3.zip",
  },
  {
    part_number: "VL-DNA-G125-A",
    title: "LED лампа VIDEX Filament VL-DNA-G125-A 3.5W E27 1800K Amber",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "3.5 W" },
      { key: "Світловий потік", value: "130 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "37 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484428" },
      { key: "Штрих-код", value: "4820246484428" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1445.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/bedda9e4-f0f1-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/2efb6f2c-f128-4700-8d9e-1430d7d5e27f.zip",
  },
  {
    part_number: "VL-DNA-G125-C",
    title: "LED лампа VIDEX Filament VL-DNA-G125-C 3.5W E27 1800K",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "3.5 W" },
      { key: "Світловий потік", value: "130 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "37 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484435" },
      { key: "Штрих-код", value: "4820246484435" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 926.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/7c21d940-f0f7-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/2ac46feb-8b30-4e78-95b0-7acd86f669a3.zip",
  },
  {
    part_number: "VL-DNA-G125-S",
    title: "LED лампа VIDEX Filament VL-DNA-G125-S 3.5W E27 1800K Smoky",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "3.5 W" },
      { key: "Світловий потік", value: "60 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 164mm" },
      { key: "Енергоефективність", value: "17 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484442" },
      { key: "Штрих-код", value: "4820246484442" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1146.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/0a19540d-f0f8-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/0caac744-f1d5-4932-a01f-fcd05f5061e0.zip",
  },
  {
    part_number: "VL-DWMC100162",
    title:
      "LED лампа VIDEX Filament VL-DWMC100162 4W E27 1800K White Chainmail style",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "180 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "100mm x 162mm" },
      { key: "Енергоефективність", value: "45 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484558" },
      { key: "Штрих-код", value: "4820246484558" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1146.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/d31a6c10-f0fd-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/69b04981-043b-4343-9da3-d6344b9ce8fd.zip",
  },
  {
    part_number: "VL-DWMC125150",
    title:
      "LED лампа VIDEX Filament VL-DWMC125150 4W E27 1800K White Chainmail style",
    params: [
      { key: "Колірна температура світла", value: "1800K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 80" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "180 Lm" },
      { key: "Максимальна сила струму", value: "38mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "20000г" },
      { key: "Напруга", value: "AC 220-240 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 150mm" },
      { key: "Енергоефективність", value: "45 Lm/W" },
      { key: "Робоча температура", value: "-20°C ~ + 40°С" },
      { key: "Кількість в упаковці", value: "1шт" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246484459" },
      { key: "Штрих-код", value: "4820246484459" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1170.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/42915784-f0fd-11ee-8382-78e7d1920004.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/aaabbd2f-0754-4560-8a76-3812abccaf60.zip",
  },
  {
    part_number: "VL-A60F-10274",
    title: "LED лампа VIDEX Filament A60F 10W E27 4100K",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "А60" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "10 W" },
      { key: "Світловий потік", value: "1350 Lm" },
      { key: "Максимальна сила струму", value: "90mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "60mm х 105mm" },
      { key: "Енергоефективність", value: "135 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "40г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299099" },
      { key: "Штрих-код", value: "4820118299099" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 151.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/59c2e72d-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/ceb1c16a-1f90-4379-bb0a-32f34bc67019.zip",
  },
  {
    part_number: "VL-A60FA-10272",
    title: "LED лампа VIDEX Filament A60FA 10W E27 2200K бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "А60" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "10 W" },
      { key: "Світловий потік", value: "1150 Lm" },
      { key: "Максимальна сила струму", value: "90mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "60mm х 105mm" },
      { key: "Енергоефективність", value: "115 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "40г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299044" },
      { key: "Штрих-код", value: "4820118299044" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 151.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/5fef9f93-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/1e00a58d-044a-4bb3-a426-6c923a51e18f.zip",
  },
  {
    part_number: "VL-A60FMD-07274",
    title: "LED лампа VIDEX Filament A60FMD 7W E27 4100K дімерна",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "А60" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "700Lm" },
      { key: "Максимальна сила струму", value: "54mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.58" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 175-250 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "60mm х 102mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло напівматове" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "40г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118295305" },
      { key: "Штрих-код", value: "4820118295305" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 130.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/1cafa5f1-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/831333a9-927b-4773-bd0e-b2386a2e52b2.zip",
  },
  {
    part_number: "VL-C37F-04143",
    title: "LED лампа VIDEX Filament C37F 4W E14 3000K",
    params: [
      { key: "Особливості", value: "Filament" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293240" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 104.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/34f4a33c-93f8-11e8-8100-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/72a973b6-3d2d-466c-bf2c-e51325e9bd28.zip",
  },
  {
    part_number: "VL-C37F-04144",
    title: "LED лампа VIDEX Filament C37F 4W E14 4100K",
    params: [
      { key: "Особливості", value: "Filament" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293257" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 80.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/3f713ce1-93f8-11e8-8100-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/d21cf470-3d62-4da2-8ab9-9a04a7790181.zip",
  },
  {
    part_number: "VL-C37F-04274",
    title: "LED лампа VIDEX Filament C37F 4W E27 4100K",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "510 Lm" },
      { key: "Максимальна сила струму", value: "30mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "37mm x 100mm" },
      { key: "Енергоефективність", value: "128 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293271" },
      { key: "Штрих-код", value: "4820118293271" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 86.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/1cafa5fb-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/b437a992-b0e4-4660-b8df-ce14102fa82c.zip",
  },
  {
    part_number: "VL-C37F-06143",
    title: "LED лампа VIDEX Filament C37F 6W E14 3000K",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "880 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "37mm x 98mm" },
      { key: "Енергоефективність", value: "147 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299112" },
      { key: "Штрих-код", value: "4820118299112" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 120.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/5fef9fa0-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/32218fc0-6b37-45ba-b6e0-6c8348665e6c.zip",
  },
  {
    part_number: "VL-C37F-06144",
    title: "LED лампа VIDEX Filament C37F 6W E14 4100K",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "880 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "37mm x 98mm" },
      { key: "Енергоефективність", value: "147 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299129" },
      { key: "Штрих-код", value: "4820118299129" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 120.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/66021d2d-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/a60e9e23-8f7f-4af7-9062-c9f621ce462f.zip",
  },
  {
    part_number: "VL-C37FA-04142",
    title: "LED лампа VIDEX Filament C37FA 4W E14 2200K",
    params: [
      { key: "Особливості", value: "Filament" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293295" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 87.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/7bf8162b-93f8-11e8-8100-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/566010e0-4517-4d85-afee-b75fb13e5f3c.zip",
  },
  {
    part_number: "VL-C37FA-04272",
    title: "LED лампа VIDEX Filament C37FA 4W E27 2200K бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "440 Lm" },
      { key: "Максимальна сила струму", value: "30mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "35mm x 100mm" },
      { key: "Енергоефективність", value: "110 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293301" },
      { key: "Штрих-код", value: "4820118293301" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 87.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/22af10f3-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/def85039-e339-422e-99f1-449c7c84a8b8.zip",
  },
  {
    part_number: "VL-C37FA-06142",
    title: "LED лампа VIDEX Filament C37FA 6W E14 2200K бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "750 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "35mm x 98mm" },
      { key: "Енергоефективність", value: "125 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299075" },
      { key: "Штрих-код", value: "4820118299075" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 120.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/66021d31-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/84f20ddf-7921-44b9-90d2-e35db8b3c033.zip",
  },
  {
    part_number: "VL-C37FD-04144",
    title: "LED лампа VIDEX Filament C37FD 4W E14 4100K дімерна",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "440 Lm" },
      { key: "Максимальна сила струму", value: "30mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "37mm x 100mm" },
      { key: "Енергоефективність", value: "110 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293769" },
      { key: "Штрих-код", value: "4820118293769" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 122.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/22af10fa-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/a5337f30-3fce-4aab-89ad-07095bbc1c30.zip",
  },
  {
    part_number: "VL-C37FMD-04144",
    title: "LED лампа VIDEX Filament C37FMD 4W E14 4100K дімерна",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "440 Lm" },
      { key: "Максимальна сила струму", value: "30mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "35mm x 100mm" },
      { key: "Енергоефективність", value: "110 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло напівматове" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "16г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118295312" },
      { key: "Штрих-код", value: "4820118295312" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 122.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/22af10fd-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/8fe3e4e2-85fd-4b05-b664-d4ce867cbc17.zip",
  },
  {
    part_number: "VL-C37Ft-06144",
    title: "LED лампа VIDEX Filament C37Ft 6W E14 4100K",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "E 14" },
      { key: "Формфактор", value: "С37" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "880 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "37mm x 120mm" },
      { key: "Енергоефективність", value: "147 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "23г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299037" },
      { key: "Штрих-код", value: "4820118299037" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 128.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/66021d36-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/5a2d7add-c17e-4c7c-9f04-07c8f1d15e4b.zip",
  },
  {
    part_number: "VL-C37FtA-06142",
    title: "LED лампа VIDEX Filament C37FtA 6W E14 2200K бронза",
    params: [
      // ... (previous params)
      { key: "Енергоефективність", value: "125 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "23г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299082" },
      { key: "Штрих-код", value: "4820118299082" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 128.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/6c7b20fd-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/b2675eac-f895-4ace-a37f-0bb7dbd0fd5a.zip",
  },
  {
    part_number: "VL-G125FAD-07272",
    title: "LED лампа VIDEX Filament G125FAD 7W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "630 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 167mm" },
      { key: "Енергоефективність", value: "90 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "80г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118295527" },
      { key: "Штрих-код", value: "4820118295527" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 290.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/22af1100-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/9befd2b8-8853-4723-b8b2-f05f4c8503a7.zip",
  },
  {
    part_number: "VL-G125FASD-05272",
    title: "LED лампа VIDEX Filament G125FASD 5W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G125" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "5 W" },
      { key: "Світловий потік", value: "340 Lm" },
      { key: "Максимальна сила струму", value: "68mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.6" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "125mm x 167mm" },
      { key: "Енергоефективність", value: "68 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "АКЦІЇ", value: "ВІДСУТНЯ БН" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "80г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118297750" },
      { key: "Штрих-код", value: "4820118297750" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 418.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/28b0df02-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/eb464f4b-97bb-4eac-9b07-b108d541bef5.zip",
  },
  {
    part_number: "VL-G200FASD-08272",
    title: "LED лампа VIDEX Filament G200FASD 8W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "8 W" },
      { key: "Світловий потік", value: "500 Lm" },
      { key: "Максимальна сила струму", value: "73mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "200mm x 300mm" },
      { key: "Енергоефективність", value: "63 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "6шт" },
      { key: "Вага", value: "320г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820246480338" },
      { key: "Штрих-код", value: "4820246480338" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1314.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/2b1397b9-994a-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/238878a4-e8f8-42c9-bcd1-96fcfc4892ae.zip",
  },
  {
    part_number: "VL-G45F-06273",
    title: "LED лампа VIDEX Filament G45F 6W E27 3000K",
    params: [
      { key: "Колірна температура світла", value: "3000К (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G45" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "880 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "45mm х 72mm" },
      { key: "Енергоефективність", value: "147 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "17г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299051" },
      { key: "Штрих-код", value: "4820118299051" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 120.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/6c7b2101-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/34cdcb91-d846-48f9-9f71-ae6d9e77e7e2.zip",
  },
  {
    part_number: "VL-G45FA-04272",
    title: "LED лампа VIDEX Filament G45FA 4W E27 2200K бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G45" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "440 Lm" },
      { key: "Максимальна сила струму", value: "30mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "45mm х 72mm" },
      { key: "Енергоефективність", value: "110 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "17г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293165" },
      { key: "Штрих-код", value: "4820118293165" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 86.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/72c47520-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/59a11318-1c43-4c1b-8a09-2a28a1f6a5fb.zip",
  },
  {
    part_number: "VL-G45FA-06272",
    title: "LED лампа VIDEX Filament G45FA 6W E27 2200K бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G45" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "750 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "45mm х 72mm" },
      { key: "Енергоефективність", value: "125 Lm/W" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118299068" },
      { key: "Штрих-код", value: "4820118299068" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 124.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/72c47524-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/ca381ccb-253a-4a9d-b50f-d65e08c3635b.zip",
  },
  {
    part_number: "VL-G45FMD-04274",
    title: "LED лампа VIDEX Filament G45FMD 4W E27 4100K дімерна",
    params: [
      { key: "Особливості", value: "Filament" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118295343" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 98.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/09e94821-db7e-11e8-810e-0025b3220fe8.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/7cf4fd0b-5d27-4682-8419-7e26672a68e9.zip",
  },
  {
    part_number: "VL-G95FAD-07272",
    title: "LED лампа VIDEX Filament G95FAD 7W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G95" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "700Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "95mm х 136mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "70г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293813" },
      { key: "Штрих-код", value: "4820118293813" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 223.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/e2304772-9948-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/bc9ebc5e-a10c-4812-bf70-b676c8edcb37.zip",
  },
  {
    part_number: "VL-G95FASD-05272",
    title: "LED лампа VIDEX Filament G95FASD 5W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G95" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "5 W" },
      { key: "Світловий потік", value: "340 Lm" },
      { key: "Максимальна сила струму", value: "37mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.6" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "95mm х 136mm" },
      { key: "Енергоефективність", value: "68 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "70г" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820118297767" },
      { key: "Штрих-код", value: "4820118297767" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 299.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/ffd6d8f5-9d5e-11e9-8123-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/447bc35b-5067-4650-81f6-34bc6626e5b6.zip",
  },
  {
    part_number: "VL-G95FD-07274",
    title: "LED лампа VIDEX Filament G95FD 7W E27 4100K дімерна",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G95" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "7W" },
      { key: "Світловий потік", value: "800 Lm" },
      { key: "Максимальна сила струму", value: "55mA" },
      { key: "Клас енергоспоживання", value: "А++" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.57" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "95mm х 136mm" },
      { key: "Енергоефективність", value: "114 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "70г" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820118294391" },
      { key: "Штрих-код", value: "4820118294391" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 205.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/72c47527-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/ee5e5848-03be-43dc-a688-8b37d5ed48a2.zip",
  },
  {
    part_number: "VL-G95FGD-04272",
    title: "LED лампа VIDEX Filament G95FGD 4W E27 2100K дімерна графіт",
    params: [
      { key: "Колірна температура світла", value: "2100K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "G95" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "100 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.6" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "95mm х 136mm" },
      { key: "Енергоефективність", value: "25 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "70г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118296593" },
      { key: "Штрих-код", value: "4820118296593" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 401.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/28b0df0f-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/29b77e15-ff91-49d8-a7a4-251c029a07f5.zip",
  },
  {
    part_number: "VL-PS160FASD-08272",
    title: "LED лампа VIDEX Filament PS160FASD 8W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "8 W" },
      { key: "Світловий потік", value: "500 Lm" },
      { key: "Максимальна сила струму", value: "73mA" },
      { key: "Клас енергоспоживання", value: "А" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.5" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "160mm x 320mm" },
      { key: "Енергоефективність", value: "63 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "10шт" },
      { key: "Вага", value: "200г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820246480345" },
      { key: "Штрих-код", value: "4820246480345" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 1122.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/311564cd-994a-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/666e9fc9-0cb6-4459-9cf7-b29c00bfb459.zip",
  },
  {
    part_number: "VL-ST64FA-10272",
    title: "LED лампа VIDEX Filament ST64FA 10W E27 2200K бронза",
    params: [
      // ... (previous params)
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20 шт" },
      { key: "Вага", value: "53г" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820246481694" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Не підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 205.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/59faebda-202e-11ec-8209-78e7d1920006.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/02bb239e-8d1b-4638-bbd1-55f57ea5ee47.zip",
  },
  {
    part_number: "VL-ST64FAD-06272",
    title: "LED лампа VIDEX Filament ST64FAD 6W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "ST64" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "600 Lm" },
      { key: "Максимальна сила струму", value: "48mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.58" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "64mm х 142mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "53г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118293837" },
      { key: "Штрих-код", value: "4820118293837" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 179.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/e2304775-9948-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/96451f81-b364-4e42-8109-1c96254ef765.zip",
  },
  {
    part_number: "VL-ST64FASD-05272",
    title: "LED лампа VIDEX Filament ST64FASD 5W E27 2200K дімерна бронза",
    params: [
      { key: "Колірна температура світла", value: "2200K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "ST64" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "5 W" },
      { key: "Світловий потік", value: "340 Lm" },
      { key: "Максимальна сила струму", value: "37mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.6" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "64mm х 142mm" },
      { key: "Енергоефективність", value: "68 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20 шт" },
      { key: "Вага", value: "53г" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820118297743" },
      { key: "Штрих-код", value: "4820118297743" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 273.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/0d4015a7-9d5f-11e9-8123-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/669f14b0-daa4-486e-9bbc-7b231024d933.zip",
  },
  {
    part_number: "VL-ST64FD-06274",
    title: "LED лампа VIDEX Filament ST64FD 6W E27 4100K  дімерна",
    params: [
      { key: "Колірна температура світла", value: "4100К (біле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "ST64" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "6 W" },
      { key: "Світловий потік", value: "700Lm" },
      { key: "Максимальна сила струму", value: "48mA" },
      { key: "Клас енергоспоживання", value: "А+" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.58" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "64mm х 142mm" },
      { key: "Енергоефективність", value: "117 Lm/W" },
      { key: "Робоча температура", value: "-25°C ~ + 50°С" },
      { key: "Матеріали", value: "Скло" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "53г" },
      { key: "Код УКТЗЕД", value: "8539 52 00 00" },
      { key: "Штрихкод", value: "4820118294407" },
      { key: "Штрих-код", value: "4820118294407" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Регулювання освітленості (димер)", value: "Підтримує" },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 171.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/7971eba8-9949-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/f917cc3e-1ab1-449b-b157-6dfdee828e97.zip",
  },
  {
    part_number: "VL-ST64FGD-04272",
    title: "LED лампа VIDEX Filament ST64FGD 4W E27 2100K дімерна графіт",
    params: [
      { key: "Колірна температура світла", value: "2100K (тепле світло)" },
      { key: "Якість світла", value: "Ra > 90" },
      { key: "Тип цоколя", value: "Е 27" },
      { key: "Формфактор", value: "ST64" },
      { key: "Особливості", value: "Filament" },
      { key: "Потужність", value: "4 W" },
      { key: "Світловий потік", value: "100 Lm" },
      { key: "Максимальна сила струму", value: "32mA" },
      { key: "Клас енергоспоживання", value: "B" },
      { key: "Кут розсіювання", value: "360°" },
      { key: "Категорія", value: "Лампи" },
      { key: "Коефіцієнт потужності", value: "0.6" },
      { key: "Ресурс роботи", value: "40000г" },
      { key: "Напруга", value: "AC 198-242 V" },
      { key: "Частота", value: "50/60 Hz" },
      { key: "Розміри", value: "64mm х 142mm" },
      { key: "Енергоефективність", value: "100 Lm/W" },
      { key: "Робоча температура", value: "-25°С + 50°С" },
      { key: "Матеріали", value: "Скло тоноване" },
      { key: "Гарантійний термін", value: "3 роки" },
      { key: "Кількість у коробі", value: "20шт" },
      { key: "Вага", value: "53г" },
      { key: "Код УКТЗЕД", value: "8539 50 00 00" },
      { key: "Штрихкод", value: "4820118296609" },
      { key: "Штрих-код", value: "4820118296609" },
      { key: "Кількість циклів Ввім/Вимк", value: "20000" },
      {
        key: "Коеф. збереження світловіддачі в кінці номінал. терміну служби",
        value: "≥94.8%",
      },
      { key: "Час запуску", value: "Миттєвий старт (<1 сек)" },
    ],
    retail: 354.0,
    currency: "UAH",
    image_link:
      "https://b2b.allegro-opt.com.ua/files/products/2f0159e7-9946-11eb-818a-0025b3220fe4.800x800.jpeg",
    additional_images:
      "https://b2b.allegro-opt.com.ua/zip/64e0cfb0-d028-4edb-8262-4594c6323505.zip",
  },
];
